language: php
sudo: required

env:
  - DB=mysql

before_script:
  - ./tests/LDAP/ldap_run.sh
  - composer self-update
  - sed -e '/"php":/d' -i composer.json
  - rm -f composer.lock
  - composer install --optimize-autoloader
  #install 0.72.3 database
  - mysql -u root -e 'create database glpitest;'
  - php scripts/cliinstall.php --db=glpitest --user=root --tests
  - php scripts/cliupdate.php --config-dir=../tests |grep -q "No migration needed." || (echo "scripts/cliupdate.php FAILED" && exit 1)
  # LDAP stuff
  - ./tests/LDAP/ldap_fixtures.sh > /dev/null
script:
  - mysql -u root -e 'select version();'
  - composer testldap

#note: default maria version is 5.5 for all main php versions list exept nightly
matrix:
  include:
    - php: 5.6
      addons:
        apt:
          packages:
            - ldap-utils
            - slapd
    - php: 7.0
      addons:
        mariadb: 10.2
        apt:
          packages:
            - ldap-utils
            - slapd

    - php: 7.1
      addons:
        mariadb: 10.1
        apt:
          packages:
            - ldap-utils
            - slapd

    - php: 7.2
      addons:
        apt:
          packages:
            - ldap-utils
            - slapd
    - php: nightly
      addons:
        apt:
          packages:
            - ldap-utils
            - slapd
  allow_failures:
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  irc:
    channels:
      - "chat.freenode.org#glpi"
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true

#exclude old branches, without tests
branches:
  except:
    - /^0\..*$/
